// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKKQgMCbN1nA0kQIdSh3GMsntjBEmvc5g',
    appId: '1:1062637598200:web:c7253bf6080e9495e8120d',
    messagingSenderId: '1062637598200',
    projectId: 'layrongutierrez-9b',
    authDomain: 'layrongutierrez-9b.firebaseapp.com',
    storageBucket: 'layrongutierrez-9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5eMuW7QSlSbQxYkGCu05mOYS-nJYKn0I',
    appId: '1:1062637598200:android:f1e047877fc117a8e8120d',
    messagingSenderId: '1062637598200',
    projectId: 'layrongutierrez-9b',
    storageBucket: 'layrongutierrez-9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8v2pJTSA-207PCdNsQJl3k78i2EK3ERI',
    appId: '1:1062637598200:ios:2e51e1faeaa5cb5be8120d',
    messagingSenderId: '1062637598200',
    projectId: 'layrongutierrez-9b',
    storageBucket: 'layrongutierrez-9b.appspot.com',
    iosBundleId: 'app.meedu.layrongutierrez9b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8v2pJTSA-207PCdNsQJl3k78i2EK3ERI',
    appId: '1:1062637598200:ios:2e51e1faeaa5cb5be8120d',
    messagingSenderId: '1062637598200',
    projectId: 'layrongutierrez-9b',
    storageBucket: 'layrongutierrez-9b.appspot.com',
    iosBundleId: 'app.meedu.layrongutierrez9b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKKQgMCbN1nA0kQIdSh3GMsntjBEmvc5g',
    appId: '1:1062637598200:web:2131697550c943e8e8120d',
    messagingSenderId: '1062637598200',
    projectId: 'layrongutierrez-9b',
    authDomain: 'layrongutierrez-9b.firebaseapp.com',
    storageBucket: 'layrongutierrez-9b.appspot.com',
  );

  
}
