// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2BlW83rxaR70Ny4uO7LGVgHOiQ5uIWlQ',
    appId: '1:265572156615:web:cda5923a8fdef9a0ca2ae2',
    messagingSenderId: '265572156615',
    projectId: 'firestore-6487d',
    authDomain: 'firestore-6487d.firebaseapp.com',
    storageBucket: 'firestore-6487d.appspot.com',
    measurementId: 'G-4FJ4RDHZTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQysgypLwjtmH9mSAKJ0XDx2IQk07RD0',
    appId: '1:265572156615:android:dcfbef71322b8dacca2ae2',
    messagingSenderId: '265572156615',
    projectId: 'firestore-6487d',
    storageBucket: 'firestore-6487d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq7BohDbHNjzxwb6KLcNE5QkCoko2KiU',
    appId: '1:265572156615:ios:d4ee0c5747a26aa0ca2ae2',
    messagingSenderId: '265572156615',
    projectId: 'firestore-6487d',
    storageBucket: 'firestore-6487d.appspot.com',
    iosBundleId: 'app.meedu.layrongutierrez9b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq7BohDbHNjzxwb6KLcNE5QkCoko2KiU',
    appId: '1:265572156615:ios:d4ee0c5747a26aa0ca2ae2',
    messagingSenderId: '265572156615',
    projectId: 'firestore-6487d',
    storageBucket: 'firestore-6487d.appspot.com',
    iosBundleId: 'app.meedu.layrongutierrez9b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2BlW83rxaR70Ny4uO7LGVgHOiQ5uIWlQ',
    appId: '1:265572156615:web:e7aa17c055956463ca2ae2',
    messagingSenderId: '265572156615',
    projectId: 'firestore-6487d',
    authDomain: 'firestore-6487d.firebaseapp.com',
    storageBucket: 'firestore-6487d.appspot.com',
    measurementId: 'G-35SGBL6HWW',
  );

  
}